- name: Générer un mot de passe aléatoire sur Windows
  hosts: windowsServer
  tasks:
    - name: Générer un mot de passe aléatoire
      set_fact:
        random_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters,digits') }}"

    - name: Définir le mot de passe pour l'utilisateur lucas
      ansible.windows.win_user:
        name: lucas
        password: "{{ random_password }}"
        state: present
      register: user_password_result

    - name: Afficher le mot de passe généré
      debug:
        msg: "Le mot de passe généré pour l'utilisateur Lucas sur la machine Windows est : {{ random_password }}"
