- name: Gestion des mots de passe
  hosts: linuxTest 
  become: true
  tasks:
    - name: Générer un mot de passe aléatoire
      shell: "openssl rand -base64 12"
      register: random_password

    - name: Définir le mot de passe pour l'utilisateur lucas
      ansible.builtin.user:
        name: lucas
        password: "{{ random_password.stdout | password_hash('sha512') }}"
        state: present
        update_password: always
      vars:
        username: "lucas"
      register: user_password_result

    - name: Afficher le mot de passe généré
      debug:
        msg: "Le mot de passe généré pour l'utilisateur lucas sur la machine Linux Test est : {{ random_password.stdout }}"
