- hosts: localhost

  roles:
    - role: ansible-modules-centreon

  vars:
    centreon_url: "http://10.10.10.2/centreon"
    centreon_api_user: "admin"
    centreon_api_pass: "Zu2B!*PU?9u6cj$8"

  tasks:
    - name: "Remove Linux Server from Centreon"
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "Linux_Server"
        state: absent
      notify: "Apply Centreon Configuration"

    - name: "Remove Linux Test from Centreon"
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "Linux_Test"
        state: absent
      notify: "Apply Centreon Configuration"

    - name: "Remove Windows Server from Centreon"
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "Windows_Server"
        state: absent
      notify: "Apply Centreon Configuration"

  handlers:
    - name: "Apply Centreon Configuration"
      centreon_poller:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        action: applycfg
